#!/usr/bin/env python3
"""Machine-generate paper_ojits/strata_auto.tex (table + prose) from scua_strata.json.
Every number in the section comes from the JSON; do not hand-edit the output."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PO = os.path.join(HERE, "outputs", "poss")
OUTTEX = os.path.join(HERE, "..", "paper_ojits", "strata_auto.tex")
d = json.load(open(os.path.join(PO, "scua_strata.json")))
r = json.load(open(os.path.join(PO, "scua_retrain.json")))

BINS = ["0--10", "10--20", "20--30", "${\\ge}$30"]
ARMS = [("base", "baseline"), ("polarmix", "PolarMix"), ("raymix", "RayMix")]
GROUPS = [("VRU", "VRU (people, rider, bike)"),
          ("small_vertical", "small-vertical (sign, pole, cone)")]


def pct(x):
    return f"{100 * x:.1f}"


def arm_cells(arm, g):
    m = d["arms"][arm]["groups_iou_mean"][g]
    s = d["arms"][arm]["groups_iou_std"][g]
    return " & ".join(f"${pct(mv)}\\,\\pm\\,{pct(sv)}$" for mv, sv in zip(m, s))


def contrast_cells(key, g):
    c = d["contrasts"][key][g]
    cells = []
    for p, lo, hi in zip(c["point"], c["lo"], c["hi"]):
        sig = not (lo <= 0.0 <= hi)
        s = f"${p:+.2f}$ {{\\scriptsize$[{lo:+.2f},{hi:+.2f}]$}}"
        cells.append(f"\\textbf{{{s}}}" if sig else s)
    return " & ".join(cells)


L = []
L.append("% AUTO-GENERATED by gen_strata_section.py from scua_strata.json — do not hand-edit.")
L.append("\\begin{table*}[t]\\centering\\footnotesize")
L.append("\\setlength{\\tabcolsep}{3pt}")
L.append("\\caption{\\textbf{Pre-registered range--class strata} (sequence~03, dedicated nine-run"
         " single-GPU arms, Sec.~\\ref{sec:setup}; group micro-IoU in \\%, mean$\\pm$std over"
         " 3~seeds; contrasts are differences of 3-seed means with paired scan-level bootstrap"
         " $95\\%$ CIs, bold $=$ CI excludes zero). Strata, groups, and metrics were fixed"
         " before scoring; all strata are shown. These are operationally relevant strata, not a"
         " validated safety metric.}")
L.append("\\label{tab:strata}")
L.append("\\begin{tabular}{llcccc}")
L.append("\\toprule")
L.append("Group & Arm / contrast & " + " & ".join(f"{b}\\,m" for b in BINS) + " \\\\ \\midrule")
for g, glabel in GROUPS:
    L.append(f"\\multirow{{5}}{{*}}{{{glabel}}}")
    for arm, alabel in ARMS:
        L.append(f" & {alabel} & {arm_cells(arm, g)} \\\\")
    L.append(f" & PolarMix $-$ baseline & {contrast_cells('polarmix-base', g)} \\\\")
    L.append(f" & RayMix $-$ PolarMix & {contrast_cells('raymix-polarmix', g)} \\\\")
    if g != GROUPS[-1][0]:
        L.append("\\midrule")
L.append("\\bottomrule")
L.append("\\end{tabular}")
L.append("\\end{table*}")
L.append("")

# prose with machine-printed numbers
pmb = d["contrasts"]["polarmix-base"]["VRU"]
rpm = d["contrasts"]["raymix-polarmix"]["VRU"]
rb = d["contrasts"]["raymix-base"]["VRU"]
allm = {a: d["arms"][a]["all_miou_mean"] for a, _ in ARMS}
pm_gain_near = 100 * (allm["polarmix"][0] - allm["base"][0])
pm_gain_far = 100 * (allm["polarmix"][3] - allm["base"][3])
pm_mean = r["arms"]["polarmix"]["mean"]
rm_mean = r["arms"]["raymix"]["mean"]

L.append(
    f"Table~\\ref{{tab:strata}} reports the pre-registered strata on a dedicated,"
    f" BN-consistent nine-run re-training of the three arms (PolarMix ${pm_mean:.2f}$,"
    f" RayMix ${rm_mean:.2f}$ overall---statistically indistinguishable, paired"
    f" ${r['contrasts']['raymix_minus_polarmix']['mean']:+.2f}$"
    f" $[{r['contrasts']['raymix_minus_polarmix']['ci95'][0]:+.2f},"
    f"{r['contrasts']['raymix_minus_polarmix']['ci95'][1]:+.2f}]$)."
    f" Three observations, in decreasing order of evidential strength."
    f" \\emph{{First}}, the composite mixing gain is strongly range-concentrated: PolarMix"
    f" adds ${pm_gain_near:+.2f}$ overall mIoU in the $0$--$10$\\,m bin but only"
    f" ${pm_gain_far:+.2f}$ beyond $30$\\,m."
    f" \\emph{{Second}}, naive mixing \\emph{{trades away far-field VRU accuracy}}: relative"
    f" to the no-mixing baseline, PolarMix changes VRU IoU by"
    f" $\\mathbf{{{pmb['point'][2]:+.2f}}}$ $[{pmb['lo'][2]:+.2f},{pmb['hi'][2]:+.2f}]$ pp at"
    f" $20$--$30$\\,m and $\\mathbf{{{pmb['point'][3]:+.2f}}}$"
    f" $[{pmb['lo'][3]:+.2f},{pmb['hi'][3]:+.2f}]$ pp beyond $30$\\,m---significant"
    f" regressions, stable across both adjacent far bins, that the overall score does not"
    f" show. \\emph{{Third}}, the sensor-consistent variant does not pay this price: RayMix"
    f" holds VRU IoU at or above the baseline in every bin (${rb['point'][2]:+.2f}$ and"
    f" $\\mathbf{{{rb['point'][3]:+.2f}}}$ $[{rb['lo'][3]:+.2f},{rb['hi'][3]:+.2f}]$ in the"
    f" far bins) and recovers $\\mathbf{{{rpm['point'][2]:+.2f}}}$"
    f" $[{rpm['lo'][2]:+.2f},{rpm['hi'][2]:+.2f}]$ and $\\mathbf{{{rpm['point'][3]:+.2f}}}$"
    f" $[{rpm['lo'][3]:+.2f},{rpm['hi'][3]:+.2f}]$ pp over PolarMix there."
    f" At matched overall utility, sensor consistency thus changes \\emph{{where}} the"
    f" errors live: naive pasting concentrates its damage in exactly the far-field"
    f" vulnerable-road-user slice that a campus planner has the least time to react to."
    f" Two cautions bound this reading: the CIs are scan-level bootstraps of 3-seed means"
    f" (seed spread is shown in the table), and these strata are operationally motivated"
    f" but not a validated safety metric; we therefore report the stratified equal-utility"
    f" trade as a finding about error geography, not a safety claim."
)
open(OUTTEX, "w").write("\n".join(L) + "\n")
print("wrote", OUTTEX)
print("VRU pm-base far bins:", pmb["point"][2:], "rm-pm far:", rpm["point"][2:])
